apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jebkinspoc
  name: jebkinspoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jebkinspoc
  template:
    metadata:
      labels:
        app: jebkinspoc
    spec:
      containers:
      -   name: jebkinspoc
          image: shadyragab/jenkinspoc:0.0.1-SNAPSHOT
          
