apiVersion: v1
kind: Service
metadata:
  labels:
    app: jebkinspoc
  name: jebkinspoc
spec:
  ports:
    - protocol: TCP
      port: 8880
      targetPort: 8080
      nodePort: 30001
  selector:
    app: jebkinspoc
  type: NodePort
